"""Run every X-round analysis script and capture the console log.

    python x_run_all.py

Writes X_console_analysis.txt next to this file (and prints the same text).

NOTE: `X_console.txt` in this directory belongs to a different round-X line
(regenerated by `X_console_build.py`, which does not know about x1-x5).  This
driver therefore deliberately does NOT touch that file, to avoid clobbering a
concurrent agent's transcript; this line's console is X_console_analysis.txt.
"""

from __future__ import annotations

import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SCRIPTS = ["x1_p83_sweep.py", "x2_contacts.py", "x3_figs2d_provenance.py",
           "x4_md_recompute.py", "x5_denominator.py"]

OUT = "X_console_analysis.txt"
chunks = [f"# {OUT} - commands and key output, round X (2026-10-02)",
          "# reproduce with:  python _coord/_round_X_20261002/analysis/"
          "x_run_all.py", ""]
for s in SCRIPTS:
    chunks.append("=" * 78)
    chunks.append(f"$ python {s}")
    chunks.append("=" * 78)
    r = subprocess.run([sys.executable, s], cwd=HERE, capture_output=True,
                       text=True, encoding="utf-8", errors="replace")
    chunks.append(r.stdout.rstrip())
    if r.returncode != 0:
        chunks.append("[STDERR] " + r.stderr.rstrip())
    chunks.append(f"[exit {r.returncode}]")
    chunks.append("")

text = "\n".join(chunks) + "\n"
with open(os.path.join(HERE, OUT), "w", encoding="utf-8") as fh:
    fh.write(text)
sys.stdout.reconfigure(errors="replace")
print(text)
